name: CalVer increment and tag
on:
  push:
    branches:
      - dev
        
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Increment and tag with CalVer
      uses: mani-sh-reddy/calver-increment@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}